#!/bin/bash
if [ -f /etc/domoticz/scripts.conf ]; then
	tts=$(grep ^ttsEngine /etc/domoticz/scripts.conf | cut -d= -f2- | tr -d '"' )
	params=$(grep ^ttsParams /etc/domoticz/scripts.conf | cut -d= -f2- | tr -d '"' )
	greting=$(grep ^ttsGreting /etc/domoticz/scripts.conf | cut -d= -f2- | tr -d '"' )
fi

if [ "$tts" == "mimic" ]; then
	/opt/mimic/bin/mimic $params -t "$greting $*"
elif [ "$tts" == "espeak" ]; then
	espeak $params "Mycroft här. $*" --stdout | aplay
fi
